[19236] Fix bitmask code generation
eProsima/Fast-DDS-Gen pull request #223
Opened 2023-09-12 13:38 UTC by JLBuenoLopez-eProsima

This PR supersedes #205

2023-09-12 13:39 UTC, JLBuenoLopez-eProsima commented
[Manual CI action](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/6160288973)

2023-09-13 05:49 UTC, richiware requested changes

2023-09-13 05:49 UTC, richiware commented on src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
> +    $bitmask.members:{ it | printf("$it.name$: %s\n", *topic & $bitmask.name$Bits::$it.name$ == $bitmask.name$Bits::$it.name$ ? "true" : "false");}; separator="\n"$
```suggestion
    $bitmask.members:{ member | printf("$member.name$: %s\n", *topic & $bitmask.name$Bits::$member.name$ == $bitmask.name$Bits::$member.name$ ? "true" : "false");}; separator="\n"$
```

2023-09-13 05:49 UTC, richiware commented on src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
> +    $bitmask.members:{ it |
```suggestion
    $bitmask.members:{ member |
```

2023-09-13 05:49 UTC, richiware commented on src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
> +        *topic |= $bitmask.name$Bits::$it.name$;
```suggestion
        *topic |= $bitmask.name$Bits::$member.name$;
```

2023-09-13 06:17 UTC, richiware requested changes
bitmask members should be initialized to 0. Right now, when a user creates an structure with a bitmask member, this one contains garbage.

2023-09-13 06:17 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
> +    $bitmask.members:{ it | printf("$it.name$: %s\n", *topic & $bitmask.name$Bits::$it.name$ == $bitmask.name$Bits::$it.name$ ? "true" : "false");}; separator="\n"$
TOC :smirk:

2023-09-13 06:18 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
> +    $bitmask.members:{ it |
:smirk:

2023-09-13 06:21 UTC, JLBuenoLopez-eProsima commented
> bitmask members should be initialized to 0. Right now, when a user creates an structure with a bitmask member, this one contains garbage.

You have just asked for an IDL-Parser v1.7.2 release! :rofl: The initial value was removed in:

* eProsima/IDL-Parser#79

2023-09-13 06:56 UTC, JLBuenoLopez-eProsima commented
[Manual CI action](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/6169028818)

2023-09-13 08:27 UTC, richiware requested changes

2023-09-13 08:27 UTC, richiware commented on src/main/java/com/eprosima/fastdds/idl/templates/SerializationSource.stg
> +    $bitmask.members:{ member | printf("$member.name$: %s\n", *topic & $bitmask.name$Bits::$member.name$ == $bitmask.name$Bits::$member.name$ ? "true" : "false");}; separator="\n"$
Print always all values true or all values false. Fix:

```suggestion
    $bitmask.members:{ member | printf("$member.name$: %s\n", ((*topic & $bitmask.name$Bits::$member.name$) == $bitmask.name$Bits::$member.name$) ? "true" : "false");}; separator="\n"$
```

2023-09-13 09:18 UTC, richiware approved these changes

2023-09-13 09:19 UTC, merged