[20566] Update fastrtps migrated headers
eProsima/Fast-DDS-Gen pull request #318
Opened 2024-03-13 11:55 UTC by elianalf

This PR updates fastrtps migrated headers:
fastrtps/utils/fixed_size_string.hpp -> fastcdr/cdr/fixed_size_string.hpp
fastrtps/utils/md5.h -> fastdds/utils/md5.h
fastrtps/rtps/common/SerializedPayload.h -> fastdds/rtps/common/SerializedPayload.h

2024-03-15 10:17 UTC, elianalf commented
Merge after 
* https://github.com/eProsima/Fast-DDS-Gen/pull/317

2024-03-15 11:28 UTC, richiware requested changes
Could you rebase on top of `4.0.x-devel`? This branch doesn't have the commit changing the product name and the tests are not passing locally.

2024-03-21 15:32 UTC, elianalf commented
CI will fail until https://github.com/eProsima/Fast-DDS-python/pull/109 is merged

2024-03-22 16:13 UTC, EduPonz approved these changes

2024-03-22 16:27 UTC, EduPonz commented
Manual CI with correct branches [here](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/8393413404)

2024-03-25 11:28 UTC, merged