Fix generated code compilation when a union uses an alias with scope
eProsima/Fast-DDS-Gen pull request #411
Opened 2024-10-08 07:30 UTC by richiware

## Description

When a union uses an alias with scope, the generated source code fails compiling. This PR fixes it.

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-10-17 10:24 UTC, MiguelCompany requested changes

2024-10-17 10:24 UTC, MiguelCompany commented on src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
> +    $union_member_destroy_call(member)$\
```suggestion
    $union_member_destroy_call(member)$
```

2024-10-17 10:44 UTC, richiware commented on src/main/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
> +    $union_member_destroy_call(member)$\
Done in 009bc8d

2024-10-17 12:53 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-10-18 08:19 UTC, MiguelCompany submitted a review, later dismissed
LGTM with green CI

2024-10-25 06:19 UTC, MiguelCompany approved these changes

2024-10-25 06:20 UTC, merged