Add custom stg templates as an option.
eProsima/Fast-DDS-Gen pull request #84
Opened 2022-01-11 12:24 UTC by ChrisFWP

Extra option added to provide a template run time. Custom user code could be generated from idl files without recompiling the generator itself.

2022-01-11 14:05 UTC, MiguelCompany commented
Hi @ChrisFWP
This looks like a nice addition indeed. Thank you for your contribution!
We will review and include it with the next release of Fast DDS Gen.

2022-02-02 08:21 UTC, richiware requested changes

2022-02-02 08:21 UTC, richiware commented on src/main/java/com/eprosima/fastdds/fastddsgen.java
>                  if (returnedValue =
```suggestion
                if (returned && returnedValue =
```

2022-06-08 06:37 UTC, richiware commented
@ChrisFWP friendly ping

2023-04-21 09:15 UTC, MiguelCompany commented
@richiware As this might come useful in the near future, I went ahead and applied your suggestions.

Would you mind reviewing again?

2023-04-21 11:15 UTC, richiware requested changes

2023-04-21 11:15 UTC, richiware commented on src/main/java/com/eprosima/fastdds/fastddsgen.java
> +                if (returned && returnedValue =
```suggestion
                if (returnedValue && returnedValue =
```

2023-04-21 11:22 UTC, MiguelCompany commented on src/main/java/com/eprosima/fastdds/fastddsgen.java
> +                if (returned && returnedValue =
0b58bdbe3b138bbb10dbbb3a70d831e0b1e4211f

2023-04-23 10:51 UTC, richiware approved these changes

2023-06-12 09:34 UTC, MiguelCompany commented
@mergifyio rebase

2023-06-12 10:25 UTC, richiware approved these changes

2023-06-12 10:25 UTC, merged